jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
        - "3.7"
        - "3.8"
        # command to install dependencies
      branches:
      only:
      - master
      - develop
      deploy:
      provider: heroku
      api_key:
      secure: yfxncvq5bdcmjxl608o5jt0nnff3nwgfqs9hkm
      app:
      master: motorent-deploy
      develop: motorent-apitest
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
        - echo $ANDROID_HOME
        - mkdir -p "$ANDROID_HOME/licenses"
        - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
      script:
        - ./gradlew build check
