jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"
      branches:
      only:
      - master
      - develop
      before_deploy:
        - cd Deployment
      deploy:
        - provider: heroku
          api_key:
            secure: neNSA50tvrMUziKhKr4TOQCXc88IIKFAEHDpg+aNMu0nAu+N4J+Nn5IroZSYrKvqIbXvQqR2fG5CcHvu1XFgrWPWs+O+cv3CRFjHrM6Kvom6+AuQjcspnph6FLWHNr45NciYEb9fZNa9/JZ2BTmWZ4cbcHdSFNgdazd3aguc96vvAe3FP3QiBhLe83RcBW6q1oKhD1V1Wmltk6Nat/kSfE6VChPVUvPUfGBDY0m3hr8trcimc8tHFEW/V/MjTPYkX43dQGAFqCacc5EXUVC9Ekz/3jEqiPSDRKeZ7SxYuHL+8G/W5OuDw1bFrmvdKIGZ4l1rSvvTpJrL8G0R05PPFOj9hcEEGWhxtzTWbFHL8I26z4CbRKD/0rFiI/Mo722rBpb20Q0PyGL03p85Q1c2wMAgnqS8+PF0Max/XBVTMWKbEgCqd3Uttzoz+QxLU2z+PD6V+QQ1vKdVLZWFylLLv74OVqzgCTxAsdgyKZvSWTPldfRkDlGl8cFXYW404VhppBteLx93QpvlZUEfyie53IyZi1F4wv0eHeIuwtvPAdXAVZlK5ieg8o5XHX6LS0XZZyyuhj1la02SmuXm7Pb0AZUQ5e300UiJwQwFUAvnbA1v/S8xjRNKQlLEnEW+4r2iDVZJPgIEKnmz5syTZtK9KJSuMeyILMahWHW64btgme0=
          app:
            master: motorent-deploy
            develop: motorent-apitest

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_install:
          - touch $HOME/.android/repositories.cfg
          - yes | sdkmanager "platforms;android-29"
          - yes | sdkmanager "build-tools;29.0.3"
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
      script:
        - ./gradlew build check
