language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
branches:
only:
- master
- develop
deploy:
provider: heroku
api_key:
secure: yfxncvq5bdcmjxl608o5jt0nnff3nwgfqs9hkm
app:
master: motorent-deploy
develop: motorent-apitest
install:
  - pip install -r Deployment/requirements.txt