jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"
      branches:
      only:
      - master
      - develop
      before_deploy:
        - cd Deployment
      deploy:
        - provider: heroku
          api_key:
            secure: dfRIpUUPGr+F3ZLCffkYcoAA1GQwT62pDKZpLSOq35Cc01IU3Fn9YS7MwzHM6taMMy5/Av+6kDT8D2pyXiB1H1RsgWhDzI9MgdwNRQ8a6jVm0udJT2NZz3xxdIai4Q8/EmlWMDidrVwyLUcYUgKJmd0ks0ha9a/vUENKa1jGA7U0m2v8LrLYDxUurZhYKIQcbTywG6yARo3i7hOsqLHA4t5uWdGzWEjQ5osUtsU/rEu9PWbj69AOy68A0oC+GtBUk2EQC2ZKs6jLQlUSixldchi5rPywr6jX7yvyLV+kiCt2wNwWpx+sQK9o790hK+XRjGbk+dv7yIpQDWVDOav8V+ceR2HEJAU1TByybuwJJfbHF2oYEcOr/6hBKaGSNAevzvg8jpXTTWd9HHZ1G0y5mg+TRfYbikrgZ0WbMRXJHgvMa/O+wgmrDFVg5P9PHP0usu+iixYvH+Q2lAvQAR3on0lR+nD54DOXbq8eM7QyXMf4cWnG6xdSB3eG6bysaC3XrOEeHIrgyDjqiSAjq3m4RS/ifliPoEsaqtVCCfBQSVXiMVbmjUsU1LqEhlJ6NSbLZt6AkDUpqXUZUse0+VR8OWt2aiAirtQIxlBSdat2pK59GOXXG1Ksk6uW0uoyYK28rw0GOSGiAixOZAXBVR4k8yDx97NTl73HV2bkmnu6uBs=
          app:
            master: motorent-deploy
            develop: motorent-apitest

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_install:
          - touch $HOME/.android/repositories.cfg
          - yes | sdkmanager "platforms;android-29"
          - yes | sdkmanager "build-tools;29.0.3"
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
      script:
        - ./gradlew build check
