jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"
      branches:
      only:
      - master
      - develop
      before_deploy:
        - cd Deployment
      deploy:
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: 
          app:
            master: motorent-deploy
            develop: motorent-apitest

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_install:
          - touch $HOME/.android/repositories.cfg
          - yes | sdkmanager "platforms;android-29"
          - yes | sdkmanager "build-tools;29.0.3"
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
      script:
        - ./gradlew build check
