jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"
      branches:
      only:
      - main
      - develop
      before_deploy:
        - cd Deployment
      deploy:
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: NQBAJunBdU795m7o50Z5yBey6yPY832fZqRPARY/kGouloWEY0BcMPS/7jvmP/wcRYxAPgcD+KpzzLnme+1aU605onQw4Zv4fU+sQP7IdWSK8rdv6pKBUH/Rd/Zola5Qc4v7T54mAW9GMf6lONESCTujTbRii/dJo9EqelJTsiMRCwZwDg5+qlXh9rFwzjvbAOh25QNo/3sRDIhSvS4UdzYjpOYDRkHQKgFWE9dTMRfvAXPGHvcCWbnDaSvtLKnCZd1hQWTN3lVsy5ifPL4Lt3qvLNXKJR8ge2aVs4JYiid0pmTSrPZHXHIoDhVznHX0j0XaJHw8k8itNV2Kws8YO4LUGvIbVV2I7c+jilBBIizwAhoJ9sBZOf/sqBCv5tQ8G1P87YIyyO8WhAR8GSNdaFBhvB0pOTbzbsQcOiwPreAA1TQkn9E+1KB3ZW8xkIhm27NSa2MVVKKhnXG+fGAFoN+XqM1j4V8GD1XpYEfnMHXCiVRg8d4g0sk9iSSR5NS2303Zig4JxEGc7dmmNPACzk5MzwEdc3JXBo+kLSUU8feCM/NXugVNiDuDy1QSsS2rO3pnMNF8UIhBC/0snVjZMYrERC75APyZkK0GbuOcbd1NvC9OSnBQgXxOFavSbHkDs/b+2yP3h49He/OnBG3oq1i4tgVSe7wo0Zp68n2H73M=
          app:
            main: motorent-deploy
            develop: motorent-apitest

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_install:
          - touch $HOME/.android/repositories.cfg
          - yes | sdkmanager "platforms;android-29"
          - yes | sdkmanager "build-tools;29.0.3"
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
      script:
        - ./gradlew build check
        - cd ..
    - language: node_js
      node_js:
        - "node"
      before_install: cd FrontWeb
      install: npm ci
      deploy:
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: NQBAJunBdU795m7o50Z5yBey6yPY832fZqRPARY/kGouloWEY0BcMPS/7jvmP/wcRYxAPgcD+KpzzLnme+1aU605onQw4Zv4fU+sQP7IdWSK8rdv6pKBUH/Rd/Zola5Qc4v7T54mAW9GMf6lONESCTujTbRii/dJo9EqelJTsiMRCwZwDg5+qlXh9rFwzjvbAOh25QNo/3sRDIhSvS4UdzYjpOYDRkHQKgFWE9dTMRfvAXPGHvcCWbnDaSvtLKnCZd1hQWTN3lVsy5ifPL4Lt3qvLNXKJR8ge2aVs4JYiid0pmTSrPZHXHIoDhVznHX0j0XaJHw8k8itNV2Kws8YO4LUGvIbVV2I7c+jilBBIizwAhoJ9sBZOf/sqBCv5tQ8G1P87YIyyO8WhAR8GSNdaFBhvB0pOTbzbsQcOiwPreAA1TQkn9E+1KB3ZW8xkIhm27NSa2MVVKKhnXG+fGAFoN+XqM1j4V8GD1XpYEfnMHXCiVRg8d4g0sk9iSSR5NS2303Zig4JxEGc7dmmNPACzk5MzwEdc3JXBo+kLSUU8feCM/NXugVNiDuDy1QSsS2rO3pnMNF8UIhBC/0snVjZMYrERC75APyZkK0GbuOcbd1NvC9OSnBQgXxOFavSbHkDs/b+2yP3h49He/OnBG3oq1i4tgVSe7wo0Zp68n2H73M=
          app:
            develop: motorent-frontweb
            main: motorent-frontweb-deploy
