jobs:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r Deployment/requirements.txt
      script:
        - python -c "print ('Python is running in Travis.')"
      branches:
      only:
      - master
      - develop
      before_deploy:
        - cd Deployment
      deploy:
        - provider: heroku
          api_key:
            secure: ZkdrVqh3XcR+LYFtQPgiffJE/hKi6IT91Roih6HnPTLm71xRDRAd8X4qns7o9hRnaXzsZhz4RpFmeD+kOo3EMVm/WD1CSAoUznBSZUagD2VDs5pbf2qcasbEfQzcdvWgXsC++IZA3wJF3ZY3BXL825EsUvdooElhl+2zZPY/6PzNDVtaQARz1sboqFo19t+693g0086KOKLRp/jdTSf0xx57qIVz6OCSn/R05Sx1I0vI8jeXr5uTxsMwbXhacKwCL06u6Q3ySc59mgSC/X3eviXfEqNcUov+n0L3EekpbQT/LP+s4dvwtixg8TuVrsn4+ZkN5fTlx3Z9MskRWNuAKza1QQvoQPqqDRYnP1CefiHxPnsMdH6H0wFW97v6KdJqR/uPo6tTK8M5w3XdS3c9HhkHFOTedXL/RuqVfxybrBjVjwAYIoMUuEmu8d6MlbD6IUOd3D6GySz5hY9g0DbE0TC401BcKqQNvAAUyXDddtdnS9EIR0ZtApXGz6TnwkpN6OXs91phTr07pvMvPyHgCYdPBumnIklQpB/hpzKLeOss1MpDBYIRqDggjcdsxsQ44z7xaMbqB9J/jP9nxN6XgCmVSV363+a8CDtOyDG07V5xnTmW7i/NzLP4AUDBurUIkxjPLhYRiXR9zf2Oy59eIxnU4Xiv0J3bcQJoDz3IGBc=
          app:
            master: motorent-deploy
            develop: motorent-apitest

    - language: android
      dist: trusty
      env:
        global:
          - ANDROID_API_LEVEL=29
          - ANDROID_BUILD_TOOLS_VERSION=29.0.3
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      android:
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_LEVEL
      addons:
        apt:
          packages:
            ant
      before_install:
          - touch $HOME/.android/repositories.cfg
          - yes | sdkmanager "platforms;android-29"
          - yes | sdkmanager "build-tools;29.0.3"
      before_script:
        - cd AndroidApp
        - chmod +x gradlew
      script:
        - ./gradlew build check
